find_path(LCMS2_INCLUDE_DIR NAMES lcms2.h PATHS ${CONAN_INCLUDE_DIRS_LCMS} NO_CMAKE_FIND_ROOT_PATH)
find_library(LCMS2_LIBRARY NAMES ${CONAN_LIBS_LCMS} PATHS ${CONAN_LIB_DIRS_LCMS} NO_CMAKE_FIND_ROOT_PATH)

MESSAGE("** LCMS2 ALREADY FOUND BY CONAN!")
SET(LCMS2_FOUND TRUE)
MESSAGE("** FOUND LCMS2:  ${LCMS2_LIBRARY}")
MESSAGE("** FOUND LCMS2 INCLUDE:  ${LCMS2_INCLUDE_DIR}")

set(LCMS2_INCLUDE_DIRS ${LCMS2_INCLUDE_DIR})
set(LCMS2_LIBRARIES ${LCMS2_LIBRARY})

mark_as_advanced(LCMS2_LIBRARY LCMS2_INCLUDE_DIR)
